---
abstract: 'util to check database''s connectivity'
author:
  - 'sunnavy <sunnavy@bestpractical.com>'
build_requires:
  Test::MockModule: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Database-CheckConnectivity
no_index:
  directory:
    - inc
    - t
requires:
  DBI: 0
  Params::Validate: 0
  UNIVERSAL::require: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
